/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/DEMO/EG4S20BG256_DEMO/demo/uart/al_ip/Double_RAM_uut.v
 ** Date	:	2019 07 23
 ** TD version	:	4.6.12906
\************************************************************/

`timescale 1ns / 1ps

module Double_RAM_uut ( 
	dia, addra, clka,
	dob, addrb, ceb, clkb
);

	output [7:0] dob;


	input  [7:0] dia;
	input  [7:0] addra;
	input  [7:0] addrb;
	input  ceb;
	input  clka;
	input  clkb;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.DATA_WIDTH_B(8),
				.ADDR_WIDTH_A(8),
				.ADDR_WIDTH_B(8),
				.DATA_DEPTH_A(256),
				.DATA_DEPTH_B(256),
				.MODE("PDPW"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(1'b1),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(),
				.dob(dob));


endmodule