# This file is generated by Anlogic Timing Wizard. 30 09 2019

#Created Clock
create_clock -period 41.6 -waveform {0 20.8} [get_ports {clk_24m}]

#Derive PLL Clocks
derive_pll_clocks -gen_basic_clock

