/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/zhang/Desktop/back/chace/githubsc/SparkRoad-V/demo_5_6_1/9_Cam_DVP/al_ip/ip_ram.v
 ** Date	:	2022 10 08
 ** TD version	:	5.6.59063
\************************************************************/

`timescale 1ns / 1ps

module img_cache ( 
	dia, addra, cea, clka,
	dob, addrb, ceb, clkb, rstb
);


	parameter DATA_WIDTH_A = 16; 
	parameter ADDR_WIDTH_A = 16;
	parameter DATA_DEPTH_A = 32800;
	parameter DATA_WIDTH_B = 16;
	parameter ADDR_WIDTH_B = 16;
	parameter DATA_DEPTH_B = 32800;
	parameter REGMODE_A    = "NOREG";
	parameter REGMODE_B    = "OUTREG";
	parameter WRITEMODE_A  = "NORMAL";
	parameter WRITEMODE_B  = "NORMAL";

	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  cea;
	input  ceb;
	input  clka;
	input  clkb;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.MODE("PDPW"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({16{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(1'b1),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.bea(1'b0),
				.web(1'b0),
				.beb(2'b00),
				.rsta(1'b0),
				.rstb(rstb),
				.doa(),
				.dob(dob));


endmodule