/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/zhang/Desktop/back/chace/githubsc/SparkRoad-V/demo_5_6_1/9_Cam_DVP/al_ip/ip_sdram.v
 ** Date	:	2022 10 08
 ** TD version	:	5.6.59063
\************************************************************/

`timescale 1ns / 1ps

module  (  );


endmodule