--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/VeriMake_C1/Desktop/lyj/mnisty/al_ip/ram_8x8x3.vhd
 -- Date	:	2024 08 15
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ram_8x8x3 IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(11 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	ceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC
	);
END ram_8x8x3;

ARCHITECTURE struct OF ram_8x8x3 IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 12,
			DATA_WIDTH_B	=> 12,
			ADDR_WIDTH_A	=> 8,
			ADDR_WIDTH_B	=> 8,
			DATA_DEPTH_A	=> 192,
			DATA_DEPTH_B	=> 192,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "000000000000"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '1',
			bea	=> (others=>'0'),
			web	=> '0',
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '0',
			rsta	=> '0',
			rstb	=> '0',
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
