--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/VeriMake_C1/Desktop/lyj/mnisty/al_ip/ram_accum.vhd
 -- Date	:	2024 08 19
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ram_accum IS
PORT (
	dout	: OUT STD_LOGIC_VECTOR(13 DOWNTO 0);

	di	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	waddr: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	raddr	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	we	: IN STD_LOGIC;
	wclk	: IN STD_LOGIC
	);
END ram_accum;

ARCHITECTURE struct OF ram_accum IS

	BEGIN
	inst : EG_LOGIC_DRAM
		GENERIC MAP (
			DATA_WIDTH_W	=> 14,
			ADDR_WIDTH_W	=> 8,
			DATA_DEPTH_W	=> 191,
			DATA_WIDTH_R	=> 14,
			ADDR_WIDTH_R	=> 8,
			DATA_DEPTH_R	=> 191,
			INIT_FILE		=> "NONE"
		)
		PORT MAP (
			di		=> di,
			waddr	=> waddr,
			we		=> we,
			wclk	=> wclk,
			do		=> dout,
			raddr	=> raddr
		);

END struct;
