/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/VeriMake_C1/Desktop/lyj/mnisty/al_ip/ram_accum.v
 ** Date	:	2024 08 19
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1 ns / 1 ps

module ram_accum ( di, waddr, we, wclk, dout, raddr );

	parameter RESETMODE = "ASYNC";
	parameter READREG = "DISABLE";
	parameter DATA_WIDTH_W = 14;
	parameter ADDR_WIDTH_W = 8;
	parameter DATA_DEPTH_W = 191;
	parameter DATA_WIDTH_R = 14;
	parameter ADDR_WIDTH_R = 8;
	parameter DATA_DEPTH_R = 191;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  wclk;
	input  we;
	input  [ADDR_WIDTH_R-1:0] raddr;

	output  [DATA_WIDTH_R-1:0] dout;

	wire [DATA_WIDTH_R-1:0] rdo;
	reg  [DATA_WIDTH_R-1:0] dout_r1;
	assign dout=(READREG == "ENABLE") ? dout_r1:rdo;

	EG_LOGIC_DRAM #(
 			.INIT_FILE("NONE"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(rdo),
			.raddr(raddr)
	);

endmodule