onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider tb_fpga
add wave -noupdate /tb_fpga/clk25MHz
add wave -noupdate /tb_fpga/clk12MHz
add wave -noupdate /tb_fpga/osc
add wave -noupdate /tb_fpga/n_rst
add wave -noupdate /tb_fpga/n_por
add wave -noupdate /tb_fpga/clk_loop
add wave -noupdate /tb_fpga/leds
add wave -noupdate /tb_fpga/buttons
add wave -noupdate /tb_fpga/exp
add wave -noupdate /tb_fpga/CS_GNDDETECT
add wave -noupdate /tb_fpga/CS_nTRST
add wave -noupdate /tb_fpga/CS_TDI
add wave -noupdate /tb_fpga/CS_TCK
add wave -noupdate /tb_fpga/CS_TMS
add wave -noupdate /tb_fpga/CS_TDO
add wave -noupdate /tb_fpga/CS_nSRST
add wave -noupdate /tb_fpga/CS_TRACECLK
add wave -noupdate /tb_fpga/CS_TRACECTL
add wave -noupdate /tb_fpga/CS_TRACEDATA
add wave -noupdate /tb_fpga/SSRAM1_CLK
add wave -noupdate /tb_fpga/SSRAM1_A
add wave -noupdate /tb_fpga/SSRAM1_DQ
add wave -noupdate /tb_fpga/SSRAM1_nBW
add wave -noupdate /tb_fpga/SSRAM1_DQP
add wave -noupdate /tb_fpga/SSRAM1_nCE1
add wave -noupdate /tb_fpga/SSRAM1_nWE
add wave -noupdate /tb_fpga/SSRAM1_nOE
add wave -noupdate /tb_fpga/SSRAM1_MODE
add wave -noupdate /tb_fpga/SSRAM1_ADVnLD
add wave -noupdate /tb_fpga/SSRAM1_ZZ
add wave -noupdate /tb_fpga/SSRAM1_nCEN
add wave -noupdate /tb_fpga/SSRAM2_CLK
add wave -noupdate /tb_fpga/SSRAM2_A
add wave -noupdate /tb_fpga/SSRAM2_DQ
add wave -noupdate /tb_fpga/SSRAM2_nBW
add wave -noupdate /tb_fpga/SSRAM2_DQP
add wave -noupdate /tb_fpga/SSRAM2_nCE1
add wave -noupdate /tb_fpga/SSRAM2_nWE
add wave -noupdate /tb_fpga/SSRAM2_nOE
add wave -noupdate /tb_fpga/SSRAM2_MODE
add wave -noupdate /tb_fpga/SSRAM2_ADVnLD
add wave -noupdate /tb_fpga/SSRAM2_ZZ
add wave -noupdate /tb_fpga/SSRAM2_nCEN
add wave -noupdate /tb_fpga/SSRAM3_CLK
add wave -noupdate /tb_fpga/SSRAM3_A
add wave -noupdate /tb_fpga/SSRAM3_DQ
add wave -noupdate /tb_fpga/SSRAM3_nBW
add wave -noupdate /tb_fpga/SSRAM3_DQP
add wave -noupdate /tb_fpga/SSRAM3_nCE1
add wave -noupdate /tb_fpga/SSRAM3_nWE
add wave -noupdate /tb_fpga/SSRAM3_nOE
add wave -noupdate /tb_fpga/SSRAM3_MODE
add wave -noupdate /tb_fpga/SSRAM3_ADVnLD
add wave -noupdate /tb_fpga/SSRAM3_ZZ
add wave -noupdate /tb_fpga/SSRAM3_nCEN
add wave -noupdate /tb_fpga/SMB_A
add wave -noupdate /tb_fpga/SMB_DQ
add wave -noupdate /tb_fpga/SMB_ETH_IRQ
add wave -noupdate /tb_fpga/SMB_ETH_nCS
add wave -noupdate /tb_fpga/SMB_nLB
add wave -noupdate /tb_fpga/SMB_nUB
add wave -noupdate /tb_fpga/SMB_nOE
add wave -noupdate /tb_fpga/SMB_nRD
add wave -noupdate /tb_fpga/SMB_nWE
add wave -noupdate /tb_fpga/SMB_nRESET
add wave -noupdate /tb_fpga/SMB_PSRAM_nCE
add wave -noupdate /tb_fpga/SMB_nZZ
add wave -noupdate /tb_fpga/UART_RXD
add wave -noupdate /tb_fpga/UART_TXD
add wave -noupdate /tb_fpga/uart_rxd_mcu
add wave -noupdate /tb_fpga/uart_txd_mcu
add wave -noupdate /tb_fpga/SPI_SCK
add wave -noupdate /tb_fpga/SPI_MOSI
add wave -noupdate /tb_fpga/SPI_MISO
add wave -noupdate /tb_fpga/SPI_nSS
add wave -noupdate /tb_fpga/VGA_HSYNC
add wave -noupdate /tb_fpga/VGA_VSYNC
add wave -noupdate /tb_fpga/VGA_R
add wave -noupdate /tb_fpga/VGA_G
add wave -noupdate /tb_fpga/VGA_B
add wave -noupdate /tb_fpga/AUD_MCLK
add wave -noupdate /tb_fpga/AUD_SCLK
add wave -noupdate /tb_fpga/AUD_LRCK
add wave -noupdate /tb_fpga/AUD_SDOUT
add wave -noupdate /tb_fpga/AUD_SDIN
add wave -noupdate /tb_fpga/AUD_nRESET
add wave -noupdate /tb_fpga/AUD_SCL
add wave -noupdate /tb_fpga/AUD_SDA
add wave -noupdate /tb_fpga/CLCD_T_SCL
add wave -noupdate /tb_fpga/CLCD_T_SDA
add wave -noupdate /tb_fpga/CLCD_CS
add wave -noupdate /tb_fpga/CLCD_RS
add wave -noupdate /tb_fpga/CLCD_WR_SCL
add wave -noupdate /tb_fpga/CLCD_RD
add wave -noupdate /tb_fpga/CLCD_RESET
add wave -noupdate /tb_fpga/CLCD_PDH
add wave -noupdate /tb_fpga/CLCD_PDL
add wave -noupdate /tb_fpga/CLCD_BL_CTRL
add wave -noupdate /tb_fpga/CLCD_SDO
add wave -noupdate /tb_fpga/CLCD_SDI
add wave -noupdate /tb_fpga/CLCD_T_CS
add wave -noupdate /tb_fpga/CLCD_T_SCK
add wave -noupdate /tb_fpga/FPGA_CONFIG_CRCERROR
add wave -noupdate /tb_fpga/FPGA_CONFIG_DATA
add wave -noupdate /tb_fpga/FPGA_CONFIG_INITDONE
add wave -noupdate /tb_fpga/FPGA_CONFIG_PRREQ
add wave -noupdate /tb_fpga/FPGA_CONFIG_PRREADY
add wave -noupdate /tb_fpga/FPGA_CONFIG_PRERROR
add wave -noupdate /tb_fpga/FPGA_CONFIG_PRDONE
add wave -noupdate /tb_fpga/DCLK
add wave -noupdate /tb_fpga/spi_nreset
add wave -noupdate /tb_fpga/nCFGRST
add wave -noupdate -divider fpga_top
add wave -noupdate /tb_fpga/u_fpga_top/OSCCLK
add wave -noupdate /tb_fpga/u_fpga_top/CB_nRST
add wave -noupdate /tb_fpga/u_fpga_top/CB_nPOR
add wave -noupdate /tb_fpga/u_fpga_top/CLKOUT
add wave -noupdate /tb_fpga/u_fpga_top/CLKIN
add wave -noupdate /tb_fpga/u_fpga_top/USER_LED
add wave -noupdate /tb_fpga/u_fpga_top/USER_PB
add wave -noupdate /tb_fpga/u_fpga_top/EXP
add wave -noupdate /tb_fpga/u_fpga_top/TP
add wave -noupdate /tb_fpga/u_fpga_top/CS_GNDDETECT
add wave -noupdate /tb_fpga/u_fpga_top/CS_nTRST
add wave -noupdate /tb_fpga/u_fpga_top/CS_TDI
add wave -noupdate /tb_fpga/u_fpga_top/CS_TCK
add wave -noupdate /tb_fpga/u_fpga_top/CS_TMS
add wave -noupdate /tb_fpga/u_fpga_top/CS_TDO
add wave -noupdate /tb_fpga/u_fpga_top/CS_nSRST
add wave -noupdate /tb_fpga/u_fpga_top/CS_TRACECLK
add wave -noupdate /tb_fpga/u_fpga_top/CS_TRACECTL
add wave -noupdate /tb_fpga/u_fpga_top/CS_TRACEDATA
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_CLK
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_A
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_DQ
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_nBW
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_DQP
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_nCE1
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_nWE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_nCEN
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_nOE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_MODE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_ADVnLD
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM1_ZZ
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_CLK
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_A
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_DQ
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_nBW
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_DQP
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_nCE1
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_nWE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_nCEN
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_nOE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_MODE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_ADVnLD
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM2_ZZ
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_CLK
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_A
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_DQ
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_nBW
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_DQP
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_nCE1
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_nWE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_nCEN
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_nOE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_MODE
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_ADVnLD
add wave -noupdate /tb_fpga/u_fpga_top/SSRAM3_ZZ
add wave -noupdate /tb_fpga/u_fpga_top/SMB_A
add wave -noupdate /tb_fpga/u_fpga_top/SMB_DQ
add wave -noupdate /tb_fpga/u_fpga_top/SMB_ETH_IRQ
add wave -noupdate /tb_fpga/u_fpga_top/SMB_ETH_nCS
add wave -noupdate /tb_fpga/u_fpga_top/SMB_nLB
add wave -noupdate /tb_fpga/u_fpga_top/SMB_nOE
add wave -noupdate /tb_fpga/u_fpga_top/SMB_nRD
add wave -noupdate /tb_fpga/u_fpga_top/SMB_nRESET
add wave -noupdate /tb_fpga/u_fpga_top/SMB_nUB
add wave -noupdate /tb_fpga/u_fpga_top/SMB_nWE
add wave -noupdate /tb_fpga/u_fpga_top/SMB_PSRAM_nCE
add wave -noupdate /tb_fpga/u_fpga_top/SMB_nZZ
add wave -noupdate /tb_fpga/u_fpga_top/UART_RXD
add wave -noupdate /tb_fpga/u_fpga_top/UART_TXD
add wave -noupdate /tb_fpga/u_fpga_top/SPI_SCK
add wave -noupdate /tb_fpga/u_fpga_top/SPI_MOSI
add wave -noupdate /tb_fpga/u_fpga_top/SPI_MISO
add wave -noupdate /tb_fpga/u_fpga_top/SPI_nSS
add wave -noupdate /tb_fpga/u_fpga_top/VGA_HSYNC
add wave -noupdate /tb_fpga/u_fpga_top/VGA_VSYNC
add wave -noupdate /tb_fpga/u_fpga_top/VGA_R
add wave -noupdate /tb_fpga/u_fpga_top/VGA_G
add wave -noupdate /tb_fpga/u_fpga_top/VGA_B
add wave -noupdate /tb_fpga/u_fpga_top/AUD_MCLK
add wave -noupdate /tb_fpga/u_fpga_top/AUD_SCLK
add wave -noupdate /tb_fpga/u_fpga_top/AUD_LRCK
add wave -noupdate /tb_fpga/u_fpga_top/AUD_SDOUT
add wave -noupdate /tb_fpga/u_fpga_top/AUD_SDIN
add wave -noupdate /tb_fpga/u_fpga_top/AUD_nRESET
add wave -noupdate /tb_fpga/u_fpga_top/AUD_SCL
add wave -noupdate /tb_fpga/u_fpga_top/AUD_SDA
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_CS
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_RS
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_WR_SCL
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_RD
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_RESET
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_PDH
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_PDL
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_BL_CTRL
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_SDO
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_SDI
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_T_SCL
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_T_SDA
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_T_CS
add wave -noupdate /tb_fpga/u_fpga_top/CLCD_T_SCK
add wave -noupdate /tb_fpga/u_fpga_top/FPGA_CONFIG_nLRST
add wave -noupdate /tb_fpga/u_fpga_top/PR_ERROR
add wave -noupdate /tb_fpga/u_fpga_top/PR_DATA
add wave -noupdate /tb_fpga/u_fpga_top/PR_REQUEST
add wave -noupdate /tb_fpga/u_fpga_top/PR_READY
add wave -noupdate /tb_fpga/u_fpga_top/CRC_ERROR
add wave -noupdate /tb_fpga/u_fpga_top/PR_DONE
add wave -noupdate /tb_fpga/u_fpga_top/clk_system
add wave -noupdate /tb_fpga/u_fpga_top/clk_zbtout
add wave -noupdate /tb_fpga/u_fpga_top/clk_25mhz_ref
add wave -noupdate /tb_fpga/u_fpga_top/clk_100hz
add wave -noupdate /tb_fpga/u_fpga_top/fclk
add wave -noupdate /tb_fpga/u_fpga_top/audio_mclk
add wave -noupdate /tb_fpga/u_fpga_top/audio_sclk
add wave -noupdate /tb_fpga/u_fpga_top/pll_locked
add wave -noupdate /tb_fpga/u_fpga_top/pll_all_locked
add wave -noupdate /tb_fpga/u_fpga_top/cs_traceclk_link
add wave -noupdate /tb_fpga/u_fpga_top/aud_lrck_link
add wave -noupdate /tb_fpga/u_fpga_top/fpga_reset_n
add wave -noupdate /tb_fpga/u_fpga_top/fpga_npor
add wave -noupdate /tb_fpga/u_fpga_top/board_rst_counter
add wave -noupdate /tb_fpga/u_fpga_top/board_rst_counter_done
add wave -noupdate /tb_fpga/u_fpga_top/cb_npor_sync
add wave -noupdate /tb_fpga/u_fpga_top/cb_nrst_sync
add wave -noupdate /tb_fpga/u_fpga_top/cs_nsrst_sync
add wave -noupdate /tb_fpga/u_fpga_top/io_exp_port_i
add wave -noupdate /tb_fpga/u_fpga_top/io_exp_port_o
add wave -noupdate /tb_fpga/u_fpga_top/io_exp_port_oen
add wave -noupdate /tb_fpga/u_fpga_top/fpga_misc
add wave -noupdate /tb_fpga/u_fpga_top/cfgint
add wave -noupdate /tb_fpga/u_fpga_top/dbg_swio_tms_o
add wave -noupdate /tb_fpga/u_fpga_top/dbg_swio_tms_en
add wave -noupdate /tb_fpga/u_fpga_top/dbg_swo_tdo_o
add wave -noupdate /tb_fpga/u_fpga_top/dbg_swo_tdo_en
add wave -noupdate /tb_fpga/u_fpga_top/zbt_sram1_dq_o
add wave -noupdate /tb_fpga/u_fpga_top/zbt_sram1_dq_oen
add wave -noupdate /tb_fpga/u_fpga_top/zbt_sram2_dq_o
add wave -noupdate /tb_fpga/u_fpga_top/zbt_sram2_dq_oen
add wave -noupdate /tb_fpga/u_fpga_top/zbt_sram3_dq_o
add wave -noupdate /tb_fpga/u_fpga_top/zbt_sram3_dq_oen
add wave -noupdate /tb_fpga/u_fpga_top/audio_sda_o_en_n
add wave -noupdate /tb_fpga/u_fpga_top/clcd_sda_o_en_n
add wave -noupdate /tb_fpga/u_fpga_top/uart_rxd_mcu_i
add wave -noupdate /tb_fpga/u_fpga_top/uart_txd_mcu_o
add wave -noupdate /tb_fpga/u_fpga_top/uart_txd_mcu_o_en
add wave -noupdate /tb_fpga/u_fpga_top/CFGCLK
add wave -noupdate /tb_fpga/u_fpga_top/nCFGRST
add wave -noupdate /tb_fpga/u_fpga_top/CFGLOAD
add wave -noupdate /tb_fpga/u_fpga_top/CFGWnR
add wave -noupdate /tb_fpga/u_fpga_top/CFGDATAIN
add wave -noupdate /tb_fpga/u_fpga_top/CFGDATAOUT
add wave -noupdate /tb_fpga/u_fpga_top/spi0_clk_out
add wave -noupdate /tb_fpga/u_fpga_top/spi0_clk_out_en_n
add wave -noupdate /tb_fpga/u_fpga_top/spi0_data_out
add wave -noupdate /tb_fpga/u_fpga_top/spi0_data_out_en_n
add wave -noupdate /tb_fpga/u_fpga_top/spi1_clk_out
add wave -noupdate /tb_fpga/u_fpga_top/spi1_clk_out_en_n
add wave -noupdate /tb_fpga/u_fpga_top/spi1_data_out
add wave -noupdate /tb_fpga/u_fpga_top/spi1_data_out_en_n
add wave -noupdate /tb_fpga/u_fpga_top/smb_data_o
add wave -noupdate /tb_fpga/u_fpga_top/smb_data_o_nen
add wave -noupdate /tb_fpga/u_fpga_top/smb_addr_extra
add wave -noupdate /tb_fpga/u_fpga_top/smb_nce
add wave -noupdate /tb_fpga/u_fpga_top/config_spiclk
add wave -noupdate /tb_fpga/u_fpga_top/config_spidi
add wave -noupdate /tb_fpga/u_fpga_top/config_spido
add wave -noupdate /tb_fpga/u_fpga_top/ivga_r
add wave -noupdate /tb_fpga/u_fpga_top/ivga_g
add wave -noupdate /tb_fpga/u_fpga_top/ivga_b
add wave -noupdate /tb_fpga/u_fpga_top/ivga_h
add wave -noupdate /tb_fpga/u_fpga_top/ivga_v
add wave -noupdate /tb_fpga/u_fpga_top/pr_active
add wave -noupdate /tb_fpga/u_fpga_top/reset_100hz_n
add wave -noupdate /tb_fpga/u_fpga_top/user_led_int
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {234482000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 284
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {233767729 ps} {235199153 ps}
